# Generated by Django 5.2.7 on 2025-11-02 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_creditnote_creditnoteitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_customers', to='management.customer'),
        ),
    ]
