# Generated by Django 5.2.7 on 2025-11-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_customer_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity_in_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
